### ISSUE TITLE
XMLHttpRequest does not have the right constructor.

### ISSUE THREAD

**Issue by smk1992** [pretenderjs/pretender#154]
When you do `new XMLHttpRequest()`, it creates an object which has the constructor referencing the native XMLHttpRequest Object instead of the XMLHttpRequest Object introduced by Pretender. So When you do `new XMLHttpRequest() instanceof XMLHttpRequest()` it returns false. This causing a problem for a third party library we are using, as it validates the object is an instance of XMLHttpRequest.

**Comment by trek** [comment]
Can you point us to which library? I imagine their use case is differentiation between `XMLHttpRequest` on most browsers and `ActiveXObject("Microsoft.XMLHTTP")` on certain versions of Internet Explorer.

When pretender starts it replaces the _value_ stored at `window.XMLHttpRequest`, so by defintion running `new XMLHttpRequest() instanceof XMLHttpRequest()` at that point _must_ return true because the global variable `XMLHttpRequest` refers to itself.

In the same way that:

```
function Y(){}

aY = new Y();
ay instance of Y;
```

MUST be true but
```
function Y(){}

aY = new Y();

window.Y = Array;
ay instance of Y
```

Would be false.

I suspect what is happening is they the library is grabbing the value stored in `window.XMLHttpRequest` before Pretender can replace the global, and they later attempt to check if request objects created after `window.XMLHttpRequest` has been replaced were constructed with the _old_ value of `window.XMLHttpRequest` (the who that is `[native code]` inspector).

For example:

```
console.log(new XMLHttpRequest() instanceof XMLHttpRequest)
// true, since the value of `var` XMLHttpRequest is, of course, `XMLHttpRequest`

var StashedXHR = XMLHttpRequest;
// store a reference to the native XHR object that is the current value of the `XMLHttpRequest` variable

new Pretender()
// start a new server, which replaces the value of `var XMLHttpRequest` with another object.

console.log(new XMLHttpRequest() instanceof XMLHttpRequest);
// true, since the value of `var` XMLHttpRequest is, of course, `XMLHttpRequest`

console.log(new XMLHttpRequest() instanceof StashedXHR)
// false. The value at `var XMLHttpRequest` is NOT the same as the value of StashedXHR

```

Here is a JSFiddle if you'd like to play around with how these global vars are handled: https://jsfiddle.net/1g0fb4hz/1/

If the library you're using compares constructors, you'd need to start a Pretender instance _before_ that library tries to grab the current value stored in `window.XMLHttpRequest` if possible.

**Comment by trek** [comment]
Closing for now. We can reopen if the @smk1992 has more info
