### ISSUE TITLE
Override a previous path handler when some headers are available

### ISSUE THREAD

**Issue by mdebbar** [pretenderjs/pretender#195]
In our test suite, we have a helper that mocks all the API paths and returns some default data. It's possible in a specific test to override one of those default handlers by simply calling `pretender.get(path, newHandler)`.

What I'm trying to achieve is override the default handler but still be able to delegate to that handler when necessary. For example:

```javascript
const pretender;

beforeEach() {
  // Create pretender instance.
  pretender = new Pretender();
  // Setup default handlers for all paths.
  setupPretenderDefaults(pretender);
}

test('...', function(assert) {
  // In this specific test, I want to have special handling of some paths if
  // the request satisfies some condition, otherwise fallback to the default handler:
  pretender.get('/my/path', function(request) {
    if (request.requestHeaders['some-header'] === 'some-value') {
      // Provide a response that's specific to this test.
      // ...
    } else {
      // In this case, we want to fallback to the default handler.
      // Default handler refers to the one previously attached by `setupPretenderDefaults()` above.
    }
  });
});
```
The `setupPretenderDefaults()` is a helper that looks something like:
```javascript
function setupPretenderDefaults(pretender) {
  pretender.get(path1, handler1);
  pretender.get(path2, handler2);
  pretender.get(path3, handler3);
  pretender.get(path4, handler4);
  pretender.get(path5, handler5);
  ...
}
```

Thanks!

**Comment by trek** [comment]
Hi @mdebbar, there's not currently an automatic way to do what your describing, but I can see the need. I don't think, however, it's a feature we would since it conflicts a bit with other functionality.

Some of that other functionality is useful to you here. `Pretender.map` can be called several times, with redefined routes overriding previously defined routes, so  if `setupPretenderDefaults` is only the code  you've shown here another more conventional style would be something like this:

```javascript
function pretenderDefaults(){
  this.get(path1, handler1);
  this.get(path2, handler2);
}

const pretender;

beforeEach() {
  pretender = new Pretender(pretenderDefaults);
}
```

That will work identically. Indeed, the library is designed for this stacking set of routes so you can use patterns like this:

```javascript
const pretender;

beforeEach() {
  pretender = new Pretender(pretenderDefaults, otherRoutes, routesForThisKindOfTest);
}
```

In the above example, the route sets defined in `pretenderDefaults`, `otherRoutes`, `routesForThisKindOfTest` all get applied. If routes defined in later route sets conflict with routes in _earlier_ sets, the last one applied "wins"


So, if you organized your `setupPretenderDefaults` code like this:

```javascript
export { 
  handler1,
  handler2
}

export default function pretenderDefaults() {
 this.get(path1, handler1);
 this.get(path2, handler2);
}
```

You could get the functionality you're looking for

```javascript
import pretenderDefaults, { handler1 } from "pretender";

const pretender;

beforeEach() {
  pretender = new Pretender(pretenderDefaults);
}

test('...', function(assert) {
  // In this specific test, I want to have special handling of some paths if
  // the request satisfies some condition, otherwise fallback to the default handler:
  pretender.get('/my/path', function(request) {
    if (request.requestHeaders['some-header'] === 'some-value') {
      // Provide a response that's specific to this test.
      // ...
    } else {
       // call path1 with the fake xhr object
       return path1(request);
    }
  });
});
```

Hope that makes sense!
