### ISSUE TITLE
Binary files are converted to strings

### ISSUE THREAD

**Issue by TimvdEijnden** [pretenderjs/pretender#72]
We use pretender to stub an Ember application, we have some sounds that are loaded and played while using the application. Loading and playing sounds fails because the pretender doesn't handle the xhr.responseType. We use Howler to load and play sounds, Howler sets the xhr.responseType to 'arraybuffer'. Pretender doesn't handle 'arraybuffer' which results in an error because Howler expects an arraybuffer. I've been trying all day to fix this in Pretender but without success so far.

This is how Howler loads an audiofile
https://github.com/goldfire/howler.js/blob/master/howler.js#L1230

**Comment by tschoartschi** [comment]
I think I run in the same issue right now. We use Ember-CLI-Mirage to stub our app which uses Pretender. When I run the acceptance tests an emscripten file is loaded. This emscripten file loads a *.mem file which is an arraybuffer. After the emscripten submitted the request the *.mem file is loaded and handed over to the emscripten file. After that the emscripten file crashes because it says the *.mem file is not an arraybuffer.

I can not tell you 100% sure if it is a problem with pretender because I can not debug the emscripten. This file is a legacy and the compiled JS is not debug friendly. Nevertheless but before we switched to Ember-CLI-Mirage and Pretender we never had any problems.

Are there any news on this issue?

**Comment by tschoartschi** [comment]
I tried to apply the changes which were made in PR#79 (https://github.com/pretenderjs/pretender/pull/79). It seems to fix the problem with the conversion to string. But this "fix" doesn't seem to be in the release versions. Nevertheless it still does not work. Now there is a new exception with our emscripten file. It says 

```Assertion failed: cannot call main when async dependencies remain! (listen on __ATMAIN__)``` 

How are requests which are defined as ```passthrough``` modified by pretender?
